using System;
using System.Collections.Generic;

namespace JVDuckDB.TypeMapping
{
    /// <summary>
    /// O2レコード（オッズ（馬連））の型マッピング
    /// </summary>
    public class O2RecordTypeMapping : RecordTypeMappingBase
    {
        public override string RecordSpec => "O2";
        
        public override Dictionary<string, Type> FieldTypeMappings => new Dictionary<string, Type>
        {
            // レース識別情報
            { "id_Year", typeof(string) },
            { "id_MonthDay", typeof(string) },
            { "id_JyoCD", typeof(string) },
            { "id_Kaiji", typeof(string) },
            { "id_Nichiji", typeof(string) },
            { "id_RaceNum", typeof(string) },
            
            // 発表時刻
            { "HappyoTime_Month", typeof(string) },
            { "HappyoTime_Day", typeof(string) },
            { "HappyoTime_Hour", typeof(string) },
            { "HappyoTime_Minute", typeof(string) },
            
            // 基本情報
            { "TorokuTosu", typeof(int) },
            { "SyussoTosu", typeof(int) },
            { "UmarenFlag", typeof(string) },
            
            // 票数
            { "TotalHyosuUmaren", typeof(long) },
            
            // オッズ情報（構造体として文字列保存 - 153個）
            { "OddsUmarenInfo_0", typeof(string) },
            { "OddsUmarenInfo_1", typeof(string) },
            { "OddsUmarenInfo_2", typeof(string) },
            { "OddsUmarenInfo_3", typeof(string) },
            { "OddsUmarenInfo_4", typeof(string) },
            { "OddsUmarenInfo_5", typeof(string) },
            { "OddsUmarenInfo_6", typeof(string) },
            { "OddsUmarenInfo_7", typeof(string) },
            { "OddsUmarenInfo_8", typeof(string) },
            { "OddsUmarenInfo_9", typeof(string) },
            { "OddsUmarenInfo_10", typeof(string) },
            { "OddsUmarenInfo_11", typeof(string) },
            { "OddsUmarenInfo_12", typeof(string) },
            { "OddsUmarenInfo_13", typeof(string) },
            { "OddsUmarenInfo_14", typeof(string) },
            { "OddsUmarenInfo_15", typeof(string) },
            { "OddsUmarenInfo_16", typeof(string) },
            { "OddsUmarenInfo_17", typeof(string) },
            { "OddsUmarenInfo_18", typeof(string) },
            { "OddsUmarenInfo_19", typeof(string) },
            { "OddsUmarenInfo_20", typeof(string) },
            { "OddsUmarenInfo_21", typeof(string) },
            { "OddsUmarenInfo_22", typeof(string) },
            { "OddsUmarenInfo_23", typeof(string) },
            { "OddsUmarenInfo_24", typeof(string) },
            { "OddsUmarenInfo_25", typeof(string) },
            { "OddsUmarenInfo_26", typeof(string) },
            { "OddsUmarenInfo_27", typeof(string) },
            { "OddsUmarenInfo_28", typeof(string) },
            { "OddsUmarenInfo_29", typeof(string) },
            { "OddsUmarenInfo_30", typeof(string) },
            { "OddsUmarenInfo_31", typeof(string) },
            { "OddsUmarenInfo_32", typeof(string) },
            { "OddsUmarenInfo_33", typeof(string) },
            { "OddsUmarenInfo_34", typeof(string) },
            { "OddsUmarenInfo_35", typeof(string) },
            { "OddsUmarenInfo_36", typeof(string) },
            { "OddsUmarenInfo_37", typeof(string) },
            { "OddsUmarenInfo_38", typeof(string) },
            { "OddsUmarenInfo_39", typeof(string) },
            { "OddsUmarenInfo_40", typeof(string) },
            { "OddsUmarenInfo_41", typeof(string) },
            { "OddsUmarenInfo_42", typeof(string) },
            { "OddsUmarenInfo_43", typeof(string) },
            { "OddsUmarenInfo_44", typeof(string) },
            { "OddsUmarenInfo_45", typeof(string) },
            { "OddsUmarenInfo_46", typeof(string) },
            { "OddsUmarenInfo_47", typeof(string) },
            { "OddsUmarenInfo_48", typeof(string) },
            { "OddsUmarenInfo_49", typeof(string) },
            { "OddsUmarenInfo_50", typeof(string) },
            { "OddsUmarenInfo_51", typeof(string) },
            { "OddsUmarenInfo_52", typeof(string) },
            { "OddsUmarenInfo_53", typeof(string) },
            { "OddsUmarenInfo_54", typeof(string) },
            { "OddsUmarenInfo_55", typeof(string) },
            { "OddsUmarenInfo_56", typeof(string) },
            { "OddsUmarenInfo_57", typeof(string) },
            { "OddsUmarenInfo_58", typeof(string) },
            { "OddsUmarenInfo_59", typeof(string) },
            { "OddsUmarenInfo_60", typeof(string) },
            { "OddsUmarenInfo_61", typeof(string) },
            { "OddsUmarenInfo_62", typeof(string) },
            { "OddsUmarenInfo_63", typeof(string) },
            { "OddsUmarenInfo_64", typeof(string) },
            { "OddsUmarenInfo_65", typeof(string) },
            { "OddsUmarenInfo_66", typeof(string) },
            { "OddsUmarenInfo_67", typeof(string) },
            { "OddsUmarenInfo_68", typeof(string) },
            { "OddsUmarenInfo_69", typeof(string) },
            { "OddsUmarenInfo_70", typeof(string) },
            { "OddsUmarenInfo_71", typeof(string) },
            { "OddsUmarenInfo_72", typeof(string) },
            { "OddsUmarenInfo_73", typeof(string) },
            { "OddsUmarenInfo_74", typeof(string) },
            { "OddsUmarenInfo_75", typeof(string) },
            { "OddsUmarenInfo_76", typeof(string) },
            { "OddsUmarenInfo_77", typeof(string) },
            { "OddsUmarenInfo_78", typeof(string) },
            { "OddsUmarenInfo_79", typeof(string) },
            { "OddsUmarenInfo_80", typeof(string) },
            { "OddsUmarenInfo_81", typeof(string) },
            { "OddsUmarenInfo_82", typeof(string) },
            { "OddsUmarenInfo_83", typeof(string) },
            { "OddsUmarenInfo_84", typeof(string) },
            { "OddsUmarenInfo_85", typeof(string) },
            { "OddsUmarenInfo_86", typeof(string) },
            { "OddsUmarenInfo_87", typeof(string) },
            { "OddsUmarenInfo_88", typeof(string) },
            { "OddsUmarenInfo_89", typeof(string) },
            { "OddsUmarenInfo_90", typeof(string) },
            { "OddsUmarenInfo_91", typeof(string) },
            { "OddsUmarenInfo_92", typeof(string) },
            { "OddsUmarenInfo_93", typeof(string) },
            { "OddsUmarenInfo_94", typeof(string) },
            { "OddsUmarenInfo_95", typeof(string) },
            { "OddsUmarenInfo_96", typeof(string) },
            { "OddsUmarenInfo_97", typeof(string) },
            { "OddsUmarenInfo_98", typeof(string) },
            { "OddsUmarenInfo_99", typeof(string) },
            { "OddsUmarenInfo_100", typeof(string) },
            { "OddsUmarenInfo_101", typeof(string) },
            { "OddsUmarenInfo_102", typeof(string) },
            { "OddsUmarenInfo_103", typeof(string) },
            { "OddsUmarenInfo_104", typeof(string) },
            { "OddsUmarenInfo_105", typeof(string) },
            { "OddsUmarenInfo_106", typeof(string) },
            { "OddsUmarenInfo_107", typeof(string) },
            { "OddsUmarenInfo_108", typeof(string) },
            { "OddsUmarenInfo_109", typeof(string) },
            { "OddsUmarenInfo_110", typeof(string) },
            { "OddsUmarenInfo_111", typeof(string) },
            { "OddsUmarenInfo_112", typeof(string) },
            { "OddsUmarenInfo_113", typeof(string) },
            { "OddsUmarenInfo_114", typeof(string) },
            { "OddsUmarenInfo_115", typeof(string) },
            { "OddsUmarenInfo_116", typeof(string) },
            { "OddsUmarenInfo_117", typeof(string) },
            { "OddsUmarenInfo_118", typeof(string) },
            { "OddsUmarenInfo_119", typeof(string) },
            { "OddsUmarenInfo_120", typeof(string) },
            { "OddsUmarenInfo_121", typeof(string) },
            { "OddsUmarenInfo_122", typeof(string) },
            { "OddsUmarenInfo_123", typeof(string) },
            { "OddsUmarenInfo_124", typeof(string) },
            { "OddsUmarenInfo_125", typeof(string) },
            { "OddsUmarenInfo_126", typeof(string) },
            { "OddsUmarenInfo_127", typeof(string) },
            { "OddsUmarenInfo_128", typeof(string) },
            { "OddsUmarenInfo_129", typeof(string) },
            { "OddsUmarenInfo_130", typeof(string) },
            { "OddsUmarenInfo_131", typeof(string) },
            { "OddsUmarenInfo_132", typeof(string) },
            { "OddsUmarenInfo_133", typeof(string) },
            { "OddsUmarenInfo_134", typeof(string) },
            { "OddsUmarenInfo_135", typeof(string) },
            { "OddsUmarenInfo_136", typeof(string) },
            { "OddsUmarenInfo_137", typeof(string) },
            { "OddsUmarenInfo_138", typeof(string) },
            { "OddsUmarenInfo_139", typeof(string) },
            { "OddsUmarenInfo_140", typeof(string) },
            { "OddsUmarenInfo_141", typeof(string) },
            { "OddsUmarenInfo_142", typeof(string) },
            { "OddsUmarenInfo_143", typeof(string) },
            { "OddsUmarenInfo_144", typeof(string) },
            { "OddsUmarenInfo_145", typeof(string) },
            { "OddsUmarenInfo_146", typeof(string) },
            { "OddsUmarenInfo_147", typeof(string) },
            { "OddsUmarenInfo_148", typeof(string) },
            { "OddsUmarenInfo_149", typeof(string) },
            { "OddsUmarenInfo_150", typeof(string) },
            { "OddsUmarenInfo_151", typeof(string) },
            { "OddsUmarenInfo_152", typeof(string) },
            
            // ヘッダー情報
            { "head_RecordSpec", typeof(string) },
            { "head_DataKubun", typeof(string) },
            { "head_MakeDate_Year", typeof(string) },
            { "head_MakeDate_Month", typeof(string) },
            { "head_MakeDate_Day", typeof(string) },
            
            // 拡張フィールド
            { "race_id", typeof(string) },
            { "happyo_datetime", typeof(DateTime) },
        };
        
        public override List<string> IndexColumns => new List<string> 
        { 
            "id_Year", "id_MonthDay", "id_JyoCD", "id_Kaiji", "id_Nichiji", "id_RaceNum" 
        };
    }
}