namespace JVDuckDB.TypeMapping
{
    /// <summary>
    /// WFレコード（払戻金（WIN5）(全件)）の型マッピング
    /// </summary>
    public class WfRecordTypeMapping : RecordTypeMappingBase
    {
        public override string RecordSpec => "WF";
        
        public override Dictionary<string, Type> FieldTypeMappings => new Dictionary<string, Type>
        {
            // 開催日
            { "KaisaiDate_Year", typeof(string) },
            { "KaisaiDate_Month", typeof(string) },
            { "KaisaiDate_Day", typeof(string) },
            
            // 発売フラグ
            { "HenkanFlag", typeof(string) },
            { "FuseiritsuFlag", typeof(string) },
            { "TekichunashiFlag", typeof(string) },
            
            // 発売票数
            { "Hatsubai_Hyo", typeof(string) },
            
            // 初期値・残高
            { "COShoki", typeof(string) },
            { "COZanDaka", typeof(string) },
            
            // レース情報（5レース分、0-based）
            { "WFRaceInfo_0", typeof(string) },
            { "WFRaceInfo_1", typeof(string) },
            { "WFRaceInfo_2", typeof(string) },
            { "WFRaceInfo_3", typeof(string) },
            { "WFRaceInfo_4", typeof(string) },
            
            // 有効票数情報（5レース分、0-based）
            { "WFYukoHyoInfo_0", typeof(string) },
            { "WFYukoHyoInfo_1", typeof(string) },
            { "WFYukoHyoInfo_2", typeof(string) },
            { "WFYukoHyoInfo_3", typeof(string) },
            { "WFYukoHyoInfo_4", typeof(string) },
            
            // 払戻金情報（構造体として文字列保存 - 243個）
            { "WFPayInfo_0", typeof(string) },
            { "WFPayInfo_1", typeof(string) },
            { "WFPayInfo_2", typeof(string) },
            { "WFPayInfo_3", typeof(string) },
            { "WFPayInfo_4", typeof(string) },
            { "WFPayInfo_5", typeof(string) },
            { "WFPayInfo_6", typeof(string) },
            { "WFPayInfo_7", typeof(string) },
            { "WFPayInfo_8", typeof(string) },
            { "WFPayInfo_9", typeof(string) },
            { "WFPayInfo_10", typeof(string) },
            { "WFPayInfo_11", typeof(string) },
            { "WFPayInfo_12", typeof(string) },
            { "WFPayInfo_13", typeof(string) },
            { "WFPayInfo_14", typeof(string) },
            { "WFPayInfo_15", typeof(string) },
            { "WFPayInfo_16", typeof(string) },
            { "WFPayInfo_17", typeof(string) },
            { "WFPayInfo_18", typeof(string) },
            { "WFPayInfo_19", typeof(string) },
            { "WFPayInfo_20", typeof(string) },
            { "WFPayInfo_21", typeof(string) },
            { "WFPayInfo_22", typeof(string) },
            { "WFPayInfo_23", typeof(string) },
            { "WFPayInfo_24", typeof(string) },
            { "WFPayInfo_25", typeof(string) },
            { "WFPayInfo_26", typeof(string) },
            { "WFPayInfo_27", typeof(string) },
            { "WFPayInfo_28", typeof(string) },
            { "WFPayInfo_29", typeof(string) },
            { "WFPayInfo_30", typeof(string) },
            { "WFPayInfo_31", typeof(string) },
            { "WFPayInfo_32", typeof(string) },
            { "WFPayInfo_33", typeof(string) },
            { "WFPayInfo_34", typeof(string) },
            { "WFPayInfo_35", typeof(string) },
            { "WFPayInfo_36", typeof(string) },
            { "WFPayInfo_37", typeof(string) },
            { "WFPayInfo_38", typeof(string) },
            { "WFPayInfo_39", typeof(string) },
            { "WFPayInfo_40", typeof(string) },
            { "WFPayInfo_41", typeof(string) },
            { "WFPayInfo_42", typeof(string) },
            { "WFPayInfo_43", typeof(string) },
            { "WFPayInfo_44", typeof(string) },
            { "WFPayInfo_45", typeof(string) },
            { "WFPayInfo_46", typeof(string) },
            { "WFPayInfo_47", typeof(string) },
            { "WFPayInfo_48", typeof(string) },
            { "WFPayInfo_49", typeof(string) },
            { "WFPayInfo_50", typeof(string) },
            { "WFPayInfo_51", typeof(string) },
            { "WFPayInfo_52", typeof(string) },
            { "WFPayInfo_53", typeof(string) },
            { "WFPayInfo_54", typeof(string) },
            { "WFPayInfo_55", typeof(string) },
            { "WFPayInfo_56", typeof(string) },
            { "WFPayInfo_57", typeof(string) },
            { "WFPayInfo_58", typeof(string) },
            { "WFPayInfo_59", typeof(string) },
            { "WFPayInfo_60", typeof(string) },
            { "WFPayInfo_61", typeof(string) },
            { "WFPayInfo_62", typeof(string) },
            { "WFPayInfo_63", typeof(string) },
            { "WFPayInfo_64", typeof(string) },
            { "WFPayInfo_65", typeof(string) },
            { "WFPayInfo_66", typeof(string) },
            { "WFPayInfo_67", typeof(string) },
            { "WFPayInfo_68", typeof(string) },
            { "WFPayInfo_69", typeof(string) },
            { "WFPayInfo_70", typeof(string) },
            { "WFPayInfo_71", typeof(string) },
            { "WFPayInfo_72", typeof(string) },
            { "WFPayInfo_73", typeof(string) },
            { "WFPayInfo_74", typeof(string) },
            { "WFPayInfo_75", typeof(string) },
            { "WFPayInfo_76", typeof(string) },
            { "WFPayInfo_77", typeof(string) },
            { "WFPayInfo_78", typeof(string) },
            { "WFPayInfo_79", typeof(string) },
            { "WFPayInfo_80", typeof(string) },
            { "WFPayInfo_81", typeof(string) },
            { "WFPayInfo_82", typeof(string) },
            { "WFPayInfo_83", typeof(string) },
            { "WFPayInfo_84", typeof(string) },
            { "WFPayInfo_85", typeof(string) },
            { "WFPayInfo_86", typeof(string) },
            { "WFPayInfo_87", typeof(string) },
            { "WFPayInfo_88", typeof(string) },
            { "WFPayInfo_89", typeof(string) },
            { "WFPayInfo_90", typeof(string) },
            { "WFPayInfo_91", typeof(string) },
            { "WFPayInfo_92", typeof(string) },
            { "WFPayInfo_93", typeof(string) },
            { "WFPayInfo_94", typeof(string) },
            { "WFPayInfo_95", typeof(string) },
            { "WFPayInfo_96", typeof(string) },
            { "WFPayInfo_97", typeof(string) },
            { "WFPayInfo_98", typeof(string) },
            { "WFPayInfo_99", typeof(string) },
            { "WFPayInfo_100", typeof(string) },
            { "WFPayInfo_101", typeof(string) },
            { "WFPayInfo_102", typeof(string) },
            { "WFPayInfo_103", typeof(string) },
            { "WFPayInfo_104", typeof(string) },
            { "WFPayInfo_105", typeof(string) },
            { "WFPayInfo_106", typeof(string) },
            { "WFPayInfo_107", typeof(string) },
            { "WFPayInfo_108", typeof(string) },
            { "WFPayInfo_109", typeof(string) },
            { "WFPayInfo_110", typeof(string) },
            { "WFPayInfo_111", typeof(string) },
            { "WFPayInfo_112", typeof(string) },
            { "WFPayInfo_113", typeof(string) },
            { "WFPayInfo_114", typeof(string) },
            { "WFPayInfo_115", typeof(string) },
            { "WFPayInfo_116", typeof(string) },
            { "WFPayInfo_117", typeof(string) },
            { "WFPayInfo_118", typeof(string) },
            { "WFPayInfo_119", typeof(string) },
            { "WFPayInfo_120", typeof(string) },
            { "WFPayInfo_121", typeof(string) },
            { "WFPayInfo_122", typeof(string) },
            { "WFPayInfo_123", typeof(string) },
            { "WFPayInfo_124", typeof(string) },
            { "WFPayInfo_125", typeof(string) },
            { "WFPayInfo_126", typeof(string) },
            { "WFPayInfo_127", typeof(string) },
            { "WFPayInfo_128", typeof(string) },
            { "WFPayInfo_129", typeof(string) },
            { "WFPayInfo_130", typeof(string) },
            { "WFPayInfo_131", typeof(string) },
            { "WFPayInfo_132", typeof(string) },
            { "WFPayInfo_133", typeof(string) },
            { "WFPayInfo_134", typeof(string) },
            { "WFPayInfo_135", typeof(string) },
            { "WFPayInfo_136", typeof(string) },
            { "WFPayInfo_137", typeof(string) },
            { "WFPayInfo_138", typeof(string) },
            { "WFPayInfo_139", typeof(string) },
            { "WFPayInfo_140", typeof(string) },
            { "WFPayInfo_141", typeof(string) },
            { "WFPayInfo_142", typeof(string) },
            { "WFPayInfo_143", typeof(string) },
            { "WFPayInfo_144", typeof(string) },
            { "WFPayInfo_145", typeof(string) },
            { "WFPayInfo_146", typeof(string) },
            { "WFPayInfo_147", typeof(string) },
            { "WFPayInfo_148", typeof(string) },
            { "WFPayInfo_149", typeof(string) },
            { "WFPayInfo_150", typeof(string) },
            { "WFPayInfo_151", typeof(string) },
            { "WFPayInfo_152", typeof(string) },
            { "WFPayInfo_153", typeof(string) },
            { "WFPayInfo_154", typeof(string) },
            { "WFPayInfo_155", typeof(string) },
            { "WFPayInfo_156", typeof(string) },
            { "WFPayInfo_157", typeof(string) },
            { "WFPayInfo_158", typeof(string) },
            { "WFPayInfo_159", typeof(string) },
            { "WFPayInfo_160", typeof(string) },
            { "WFPayInfo_161", typeof(string) },
            { "WFPayInfo_162", typeof(string) },
            { "WFPayInfo_163", typeof(string) },
            { "WFPayInfo_164", typeof(string) },
            { "WFPayInfo_165", typeof(string) },
            { "WFPayInfo_166", typeof(string) },
            { "WFPayInfo_167", typeof(string) },
            { "WFPayInfo_168", typeof(string) },
            { "WFPayInfo_169", typeof(string) },
            { "WFPayInfo_170", typeof(string) },
            { "WFPayInfo_171", typeof(string) },
            { "WFPayInfo_172", typeof(string) },
            { "WFPayInfo_173", typeof(string) },
            { "WFPayInfo_174", typeof(string) },
            { "WFPayInfo_175", typeof(string) },
            { "WFPayInfo_176", typeof(string) },
            { "WFPayInfo_177", typeof(string) },
            { "WFPayInfo_178", typeof(string) },
            { "WFPayInfo_179", typeof(string) },
            { "WFPayInfo_180", typeof(string) },
            { "WFPayInfo_181", typeof(string) },
            { "WFPayInfo_182", typeof(string) },
            { "WFPayInfo_183", typeof(string) },
            { "WFPayInfo_184", typeof(string) },
            { "WFPayInfo_185", typeof(string) },
            { "WFPayInfo_186", typeof(string) },
            { "WFPayInfo_187", typeof(string) },
            { "WFPayInfo_188", typeof(string) },
            { "WFPayInfo_189", typeof(string) },
            { "WFPayInfo_190", typeof(string) },
            { "WFPayInfo_191", typeof(string) },
            { "WFPayInfo_192", typeof(string) },
            { "WFPayInfo_193", typeof(string) },
            { "WFPayInfo_194", typeof(string) },
            { "WFPayInfo_195", typeof(string) },
            { "WFPayInfo_196", typeof(string) },
            { "WFPayInfo_197", typeof(string) },
            { "WFPayInfo_198", typeof(string) },
            { "WFPayInfo_199", typeof(string) },
            { "WFPayInfo_200", typeof(string) },
            { "WFPayInfo_201", typeof(string) },
            { "WFPayInfo_202", typeof(string) },
            { "WFPayInfo_203", typeof(string) },
            { "WFPayInfo_204", typeof(string) },
            { "WFPayInfo_205", typeof(string) },
            { "WFPayInfo_206", typeof(string) },
            { "WFPayInfo_207", typeof(string) },
            { "WFPayInfo_208", typeof(string) },
            { "WFPayInfo_209", typeof(string) },
            { "WFPayInfo_210", typeof(string) },
            { "WFPayInfo_211", typeof(string) },
            { "WFPayInfo_212", typeof(string) },
            { "WFPayInfo_213", typeof(string) },
            { "WFPayInfo_214", typeof(string) },
            { "WFPayInfo_215", typeof(string) },
            { "WFPayInfo_216", typeof(string) },
            { "WFPayInfo_217", typeof(string) },
            { "WFPayInfo_218", typeof(string) },
            { "WFPayInfo_219", typeof(string) },
            { "WFPayInfo_220", typeof(string) },
            { "WFPayInfo_221", typeof(string) },
            { "WFPayInfo_222", typeof(string) },
            { "WFPayInfo_223", typeof(string) },
            { "WFPayInfo_224", typeof(string) },
            { "WFPayInfo_225", typeof(string) },
            { "WFPayInfo_226", typeof(string) },
            { "WFPayInfo_227", typeof(string) },
            { "WFPayInfo_228", typeof(string) },
            { "WFPayInfo_229", typeof(string) },
            { "WFPayInfo_230", typeof(string) },
            { "WFPayInfo_231", typeof(string) },
            { "WFPayInfo_232", typeof(string) },
            { "WFPayInfo_233", typeof(string) },
            { "WFPayInfo_234", typeof(string) },
            { "WFPayInfo_235", typeof(string) },
            { "WFPayInfo_236", typeof(string) },
            { "WFPayInfo_237", typeof(string) },
            { "WFPayInfo_238", typeof(string) },
            { "WFPayInfo_239", typeof(string) },
            { "WFPayInfo_240", typeof(string) },
            { "WFPayInfo_241", typeof(string) },
            { "WFPayInfo_242", typeof(string) },
            
            // 予約フィールド
            { "reserved1", typeof(string) },
            { "reserved2", typeof(string) },
            
            // ヘッダー情報
            { "head_RecordSpec", typeof(string) },
            { "head_DataKubun", typeof(string) },
            { "head_MakeDate_Year", typeof(string) },
            { "head_MakeDate_Month", typeof(string) },
            { "head_MakeDate_Day", typeof(string) },
        };
        
        public override List<string> IndexColumns => new List<string> 
        { 
            "KaisaiDate_Year", "KaisaiDate_Month", "KaisaiDate_Day"
        };
    }
}